# Copyright 2021 American Express
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing
# permissions and limitations under the License.

---
description: This module checks for passwords and secrets in files. It includes rules for identifying potential default passwords, as well as patterns that may indicate the presence of sensitive information such as API keys, access tokens, and database connection strings. The rules use regular expressions to match common naming conventions for passwords and secrets, and they also include post-processing steps to extract the relevant information for further analysis or redaction.
Searcharea: body
rules:
  - Code: 1002
    Pattern: (?i)"p[a4@][s$][s$]w[o0]rd([#!@]?(123)?)?"
    Caption: Potential default password in file
    Category: password-secret
    Example: '"password"'
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: password
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1061
    Pattern: (?i)['"]ch[a@]ngeme['"]
    Caption: Potential default password in file
    Category: password-secret
    Example: '"changeme"'
    SolutionID: 8
    Severity: 2
    Confidence: 4
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1068
    Pattern: "(?i)1q2w3e4r"
    Caption: Potential default password in file
    Category: password-secret
    Example: 1q2w3e4r
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1070
    Pattern: "(?i)kafka123"
    Caption: Potential default password in file
    Category: password-secret
    Example: kafka123
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1071
    Pattern: "(?i)kafkae[1-3]"
    Caption: Potential default password in file
    Category: password-secret
    Example: kafkae1
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1072
    Pattern: "(?i)admin[1-3]"
    Caption: Potential default password in file
    Category: password-secret
    Example: admin1
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1073
    Pattern: "(?i)1qaz@WSX"
    Caption: Potential default password in file
    Category: password-secret
    Example: 1qaz@WSX
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1074
    Pattern: "(?i)letmein"
    Caption: Potential default password in file
    Category: password-secret
    Example: letmein
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1074
    Pattern: "(?i)w2e3r4t5"
    Caption: Potential default password in file
    Category: password-secret
    Example: password = 'w2e3r4t5'
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 1074
    Pattern: "(?i)password.+(winter|spring|summer|autumn|fall)"
    Caption: Potential default password in file
    Category: password-secret
    Example: password = 'autumn2019'
    SolutionID: 8
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-521
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3001
    Pattern: (?i)(['"]?\w*password['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]))
    Caption: Potential password in file
    Category: password-secret
    Example: password = 'foobar'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3003
    Pattern: (?i)(['"]?pw['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential password in file
    Category: password-secret
    Example: pw='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 4
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3004
    Pattern: (?i)(['"]?pass['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential password in file
    Category: password-secret
    Example: pass='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 4
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3005
    Pattern: (?i)(['"]?pword['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential password in file
    Category: password-secret
    Example: pword='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 4
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3006
    Pattern: (?i)(['"]?passphrase['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential passphrase in file
    Category: password-secret
    Example: passphrase='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3007
    Pattern: "(?i)(<[^(><.)]?(password)[^(><.)]?>[^(><.)]+</[^(><.)]?(password)[^(><.)]?>)"
    Caption: Potential password in file
    Category: password-secret
    Example: "<password>foobar</password>"
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3008
    Pattern: "(?i)(<[^(><.)]*passphrase[^(><.)]*>[^(><.)]+</[^(><.)]*passphrase[^(><.)]*>)"
    Caption: Potential passphrase in file
    Category: password-secret
    Example: "<passphrase>foobar</passphrase>"
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3021
    Pattern: (?i)(['"]?passwrd['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential password in file
    Category: password-secret
    Example: passwrd = 'foobar'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3022
    Pattern: (?i)(['"]?passwd['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential password in file
    Category: password-secret
    Example: passwd = 'foobar'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3026
    Pattern: (?i)(['"]?secret['"]?[ \t]*[:=][ \t]*(['"][^'"]{3,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]+))
    Caption: Potential secret in file
    Category: password-secret
    Example: secret = 'foobar'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3027
    Pattern: (?i)(['"]?secretkey['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential secret in file
    Category: password-secret
    Example: secretKey = 'foobar'
    SolutionID: 1
    Severity: 1
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3029
    Pattern: "(?i)(oauth.appSecret[ \\t]*[:=][ \\t]*([^\\s]+))"
    Caption: Potential secret in file
    Category: password-secret
    Example: oauth.appSecret = 'foobar'
    SolutionID: 1
    Severity: 1
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3030
    Pattern: "(?i)(AWS Secret Access Key [^:]*:[ \\t]*([^\\s]+))"
    Caption: Potential secret in file
    Category: password-secret
    Example: 'AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKFE'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3032
    Pattern: (?i)(appSecret[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential secret in file
    Category: password-secret
    Example: appsecret='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3033
    Pattern: (?i)(client[_-]?secret[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential secret in file
    Category: password-secret
    Example: clientsecret='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3084
    Pattern: (?i)(['"]?(Authorization)?['"]?[ \t]*[:=]?[ \t]*['"]?Basic[ \t]*[A-Za-z0-9+=\/]{5,}['"]?)
    Caption: Potential Basic Auth token in file
    Category: password-secret
    Example: 'Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=='
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: basicAuth
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3034
    Pattern: (?i)(['"]client[_-]?secret['"][ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential secret in file
    Category: password-secret
    Example: "'client_secret': 'foobar'"
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3035
    Pattern: (?i)(['"]?auth[_-]?key['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential secret in file
    Category: password-secret
    Example: auth_key='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3036
    Pattern: (?i)(['"]?secret[_-]?key['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential secret in file
    Category: password-secret
    Example: secret_key='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3037
    Pattern: (?i)(['"]?_token['"]?[ \t]*[:=][ \t]*['"]?[0-9a-zA-Z\.\-_\\U]{12,}['"]?)
    Caption: Potential secret in file
    Category: password-secret
    Example: auth_token='xxx123xxx345xxx678'
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3040
    Pattern: (?i)['"]?(google_access_token)['"]?[ \t]*[:=][ \t]*['"][^'"]{4,}['"]
    Caption: Potential secret in file
    Category: password-secret
    Example: google_access_token = "test"
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3041
    Pattern: "(?i)(ya29\\.[0-9a-zA-Z_\\-]{68})"
    Caption: Potential secret in file
    Category: password-secret
    Example: ya29Xaz65xnSOi45O5wyRaaeONDHqenVAMXmxObLMZq-vQihlleznZAbCHHWr6Gz3J7DKuyQf
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3042
    Pattern: (?i)['"]?(google_api)['"]?[ \t]*[:=][ \t]*['"][^'"]{4,}['"]
    Caption: Potential secret in file
    Category: password-secret
    Example: google_api = "test"
    SolutionID: 1
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3043
    Pattern: "(?i)(AIzaSy[0-9a-zA-Z_\\-]{33})"
    Caption: Potential secret in file
    Category: password-secret
    Example: AIzaSyQ4kHseoBZiO7anxQJ2IzlfzfMLjNU5ma_
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3044
    Pattern: (?i)['"]?(slack_xoxb)['"]?[ \t]*[:=][ \t]*['"][^'"]{4,}['"]
    Caption: Potential secret in file
    Category: password-secret
    Example: slack_xoxb = "test"
    SolutionID: 1
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3045
    Pattern: "(?i)(xox[pboa]-\\d+-\\d+-\\d+-[0-9a-f]+)"
    Caption: Potential secret in file
    Category: password-secret
    Example: xoxa-123-123-123-012af
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3046
    Pattern: "(?i)(Mapbox Secure Key)"
    Caption: Potential secret in file
    Category: password-secret
    Example: Mapbox Secure Key
    SolutionID: 1
    Severity: 2
    Confidence: 3
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3047
    Pattern: "(?i)(xox[sp]-[0-9]{10}-[0-9]{10}-[0-9]{12}-[a-z0-9]{32})"
    Caption: Potential secret in file
    Category: password-secret
    Example: xoxs-0260321744-0287945347-015035651542-oxtp6n0z7yibj63vndve9gsej96k5k4s
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3048
    Pattern: "(?i)(\\/\\/registry\\.npmjs\\.org\\/:_authToken=[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})"
    Caption: Potential secret in file
    Category: password-secret
    Example: "//registry.npmjs.org/:_authToken=77a13b56-f6c9-0294-57b0-b635f6260064"
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 3049
    Pattern: (?i)(['"]?pwd['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential password in file
    Category: password-secret
    Example: pwd='xxxx'
    SolutionID: 1
    Severity: 2
    Confidence: 4
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3057
    Pattern: (?i)(['"]?\w*password['"]?[ \t]*[:=][ \t]*([0-9a-z\-_@#! %\^\?\*&\$~]{4,}))
    Caption: Potential password in file
    Category: password-secret
    Example: password=foobar
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3060
    Pattern: "(?i)(mysql|oracle|odbc|jdbc|postgresql|mongodb|mongo|couchbase)://\\w{3,}:\\w{3,}(@[^/]{3,}/)"
    Caption: Potential insecure db connection string
    Category: password-secret
    Example: mysql://joeblow:mypassword@foo.bar.baz/
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3065
    Pattern: heroku.{0,55}[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}
    Caption: Heroku key
    Category: password-secret
    Example: 'heroku: ''A0AAA0AA-aAaa-AAAA-aaAA-Aa00AaAA0a0A'''
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3066
    Pattern: (github)[ \t]*[:=][ \t]*['"'"'"][a-zA-Z0-9]{35,40}['"'"'"]
    Caption: Github key
    Category: password-secret
    Example: 'github: ''aaaAaA0A0a00aAaA0a0aA0AAaaaAAa0Aa00'''
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3067
    Pattern: facebook.{0,55}['"'"'"][0-9a-f]{32,255}['"'"'"]
    Caption: Facebook key
    Category: password-secret
    Example: 'facebook: ''a00000aa0aaa0aa0a00aa00a00000aaa0a000a0a0aaa0a0a0a00aa00a000aaa0'''
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3068
    Pattern: twitter.{0,55}['"'"'"][a-zA-Z0-9]{35,44}['"'"'"]
    Caption: Twitter key
    Category: password-secret
    Example: 'twitter: ''0aaAaA0AAAA0000a0a0A0a0aaa0AaAA0a0a'''
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: ''
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259
  - Code: 3075
    Pattern: (?i)(['"]?credential[s]?['"]?[ \t]*[:=][ \t]*(['"][^'"]{4,}['"]|[0-9a-z\-_@#!%\^\?\*&\$~]{4,}))
    Caption: Potential secret in file
    Category: password-secret
    Example: "'credential': 'foobar'"
    SolutionID: 1
    Severity: 2
    Confidence: 2
    Postprocess: password
    CWE:
      - CWE-798
      - CWE-321
      - CWE-312
  - Code: 5001
    Pattern: ('[^'\s]{12,64}'|"[^"\s]{12,64}")
    Caption: High entropy string -- potential password
    Category: password-secret
    Example: "'b6SxM4UwRm1dBqTG4zIVU6rcBy1QhnfQKmSZOnmR6fS7ZvuCxf1C1uQFNI9CVWzH'"
    SolutionID: 1
    Severity: 3
    Confidence: 3
    Postprocess: entropy
    CWE:
      - CWE-798
      - CWE-312
      - CWE-257
      - CWE-259


